name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run
        run: echo 'Hello World!' #dotnet run --project TodoBasic/Todos.csproj
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test
        uses: matt-ball/newman-action@master
#        with:
#          collection: .github/workflows/postman_collection.json
